export interface BotIdentity {
  name: string;
  color: string;
}

export const BOT_IDENTITIES: BotIdentity[] = [
  { name: 'Cobalt', color: '#0047AB' },
  { name: 'Thenerium', color: '#8A2BE2' },
  { name: 'Quartz', color: '#F0F8FF' },
  { name: 'Améthyste', color: '#9966CC' },
  { name: 'Rubis', color: '#E0115F' },
  { name: 'Saphir', color: '#0F52BA' },
  { name: 'Émeraude', color: '#50C878' },
  { name: 'Diamant', color: '#B9F2FF' },
  { name: 'Or', color: '#FFD700' },
  { name: 'Argent', color: '#C0C0C0' },
  { name: 'Bronze', color: '#CD7F32' },
  { name: 'Cuivre', color: '#B87333' },
  { name: 'Fer', color: '#A19D94' },
  { name: 'Titane', color: '#878681' },
  { name: 'Platine', color: '#E5E4E2' },
  { name: 'Mithril', color: '#C0C0C0' },
  { name: 'Orichalque', color: '#E49B0F' },
  { name: 'Adamantium', color: '#71797E' },
  { name: 'Vibranium', color: '#6A0DAD' },
  { name: 'Obsidienne', color: '#141414' },
  { name: 'Onyx', color: '#353839' },
  { name: 'Opale', color: '#A8C3BC' },
  { name: 'Topaze', color: '#FFC87C' },
  { name: 'Jade', color: '#00A86B' },
  { name: 'Malachite', color: '#0BDA51' },
  { name: 'Lapis-Lazuli', color: '#26619C' },
  { name: 'Bismuth', color: '#987654' },
  { name: 'Tungstène', color: '#5A5A5A' },
  { name: 'Uranium', color: '#1C542D' },
  { name: 'Plutonium', color: '#E03C31' },
  { name: 'Palladium', color: '#919390' },
  { name: 'Iridium', color: '#B0B0B0' },
  { name: 'Osmium', color: '#4682B4' },
  { name: 'Zirconium', color: '#DCDCDC' },
  { name: 'Pro_Gamer_du_69', color: '#FF0000' },
  { name: 'Pro_Gamer_du_75', color: '#0000FF' },
  { name: 'xX_DarkSasuke_Xx', color: '#000000' },
  { name: 'The_Killer_99', color: '#8B0000' },
  { name: 'PGM_du_93', color: '#008000' },
  { name: 'Noob_Slayer', color: '#DC143C' },
  { name: 'xX_Sniper_Xx', color: '#228B22' },
  { name: 'G@mer_B0y', color: '#1E90FF' },
  { name: 'Toxic_Player', color: '#32CD32' },
  { name: 'TryHarder_FR', color: '#00008B' },
  { name: 'Le_Boss_du_Game', color: '#FFD700' },
  { name: 'Alpha_Wolf', color: '#708090' },
  { name: 'Shadow_Ninja', color: '#2F4F4F' },
  { name: 'K1ll3r_Pr0', color: '#B22222' },
  { name: 'Glitch_Master', color: '#00FF00' },
  { name: 'Rage_Quit', color: '#FF4500' },
  { name: 'MVP_2026', color: '#FFD700' },
  { name: 'xX_Demon_Xx', color: '#8B0000' },
  { name: 'Pro_Gamer_du_13', color: '#4169E1' },
  { name: 'Le_Sniper_Fou', color: '#8B4513' },
  { name: 'King_of_Agar', color: '#FF8C00' },
  { name: 'Cell_Eater', color: '#3CB371' },
  { name: 'Blob_Destroyer', color: '#9932CC' },
  { name: 'xX_Venom_Xx', color: '#006400' },
  { name: 'PGM_Forever', color: '#4682B4' },
  { name: 'Dark_Knight', color: '#191970' },
  { name: 'The_Legend', color: '#DAA520' },
  { name: 'Master_Chief', color: '#556B2F' },
  { name: 'xX_Ghost_Xx', color: '#F8F8FF' },
  { name: 'Ninja_du_78', color: '#2F4F4F' },
  { name: 'Pro_Gamer_du_59', color: '#1E90FF' },
  { name: 'Lord_of_Blobs', color: '#8A2BE2' },
  { name: 'Toxic_Slime', color: '#7CFC00' },
  { name: 'Lune', color: '#F4F6F0' },
  { name: 'Andromeda', color: '#301934' },
  { name: 'Soleil', color: '#FDB813' },
  { name: 'Mercure', color: '#B5A7A7' },
  { name: 'Vénus', color: '#E3BB76' },
  { name: 'Terre', color: '#2B82C9' },
  { name: 'Mars', color: '#C1440E' },
  { name: 'Jupiter', color: '#D39C7E' },
  { name: 'Saturne', color: '#EAD6B8' },
  { name: 'Uranus', color: '#4FD0E7' },
  { name: 'Neptune', color: '#274687' },
  { name: 'Pluton', color: '#9CA6B7' },
  { name: 'Sirius', color: '#FFFFFF' },
  { name: 'Véga', color: '#9BC4E2' },
  { name: 'Orion', color: '#4B0082' },
  { name: 'Cassiopée', color: '#8A2BE2' },
  { name: 'Pégase', color: '#E6E6FA' },
  { name: 'Centaure', color: '#D2B48C' },
  { name: 'VoieLactée', color: '#E0B0FF' },
  { name: 'TrouNoir', color: '#000000' },
  { name: 'Quasar', color: '#FF4500' },
  { name: 'Pulsar', color: '#00FFFF' },
  { name: 'Supernova', color: '#FFD700' },
  { name: 'Comète', color: '#ADD8E6' },
  { name: 'Météore', color: '#A9A9A9' },
  { name: 'Astéroïde', color: '#696969' },
  { name: 'Nébuleuse', color: '#FF1493' },
  { name: 'Titan', color: '#D2B48C' },
  { name: 'Europa', color: '#FDF5E6' },
  { name: 'Ganymède', color: '#D3D3D3' },
  { name: 'Callisto', color: '#8B4513' },
  { name: 'Io', color: '#FFFF00' },
  { name: 'Phobos', color: '#A0522D' },
  { name: 'Robibou', color: '#FF69B4' },
  { name: 'Ribobozo', color: '#FFB6C1' },
  { name: 'Eliotoumtoum', color: '#87CEEB' },
  { name: 'Eliotitos', color: '#00BFFF' },
  { name: 'Olibom', color: '#32CD32' },
  { name: 'Olibomix', color: '#00FA9A' },
  { name: 'Baamix', color: '#FFA500' },
  { name: 'Gigi', color: '#FFC0CB' },
  { name: 'Coton', color: '#FFFFFF' },
];

export const BOT_COLORS: Record<string, string> = Object.fromEntries(
  BOT_IDENTITIES.map((b) => [b.name, b.color]),
);

/** Détermine si un ID de joueur correspond à un bot d'après son préfixe déterministe (`bot-`). */
export function isBotId(id: string): boolean {
  return id.startsWith('bot-');
}
